CONFIGDIR="${ZDOTDIR:-$HOME}/.config/zsh"

source "${CONFIGDIR}/keybindings.zsh"

# export homebrew
export PATH=$PATH:/opt/homebrew/bin

# export webstorm
export PATH=$PATH:/Applications/WebStorm.app/Contents/MacOS

